### PR TITLE
Mitchel about and goals section

### PR DESCRIPTION
**Pull request by zootechdrum**
This looks good. I will copy and paste to the same index.html file. (If it gets approved)

### CODE REVIEW

**Review by zootechdrum — COMMENTED** [review]
Just wondering what are the string of comments that start at line 2?

**Comment by grafkendo** [comment]
@zootechdrum  the comments on line 2 are to help compatibility with older versions of explorer. my ide puts those in as part of a boilerplate snippet. I'm fine with removing them if you like.

**Comment by tonynguyen111997** [comment]
@grafkendo The about and goals looks great, but when the screen size is lowered the button to expand the navbar does not work. Other than that it's perfect.

**Comment by grafkendo** [comment]
@tonynguyen111997  ill look at the navbar issue thanks.

**Review by zootechdrum — COMMENTED** [review]
I like it. I will see what it looks like soon

**Comment by grafkendo** [comment]
@tonynguyen111997 for me locally, the nave bar toggle works...

**Review by zootechdrum — COMMENTED** [review]
There is a overlap between your h1 tag and p tag on the navbar. Honestly, i would get rid of it since we are going to be using Tonys nav anyway. I love the layout though. very good work. I think we can copy and paste the section as soon as those changes are made.

**Comment by tonynguyen111997** [comment]
If the issue isn't happening on your end @grafkendo it may just be an issue on mine. I checked again and for some reason the navbar-collapse was getting overlapped by the goals and it also had no background-color on my machine for some reason causing it to be nearly invisible. I'll have to look into this further, but for now please merge it into master.

**Review by tonynguyen111997 — APPROVED** [review]
Just left a comment on it..

**Comment by zootechdrum** [comment]
The reason I closed this pull request is because I opened it. Mitchel never opened a pull request, he instead pushed a branch to the remote repo. I was still playing around with the site and opened a pull request on his new branch making me the other. I will close it and ask him to open a new one making him the author.

**Pull request closed without merging**
