### PR TITLE
init Bootstrap

### PR DESCRIPTION
**Pull request by CRivera19**

### CODE REVIEW

**Comment by grafkendo** [comment]
NIce what did you do to resolve the conflict?

**Comment by zootechdrum** [comment]
@grafkendo I deleted the conflicting code. 
The issue there was replicated code because Tony and @CRivera19 added the head part. Because, @CRivera19 code already comes with the bootstrap CDN and the JQuery CDN i kept that one instead. Please pull new repo to have the most up to date code. Basically I deleted Tony's code merged the master with the blank index.html and that fixed the issue.

**Comment by grafkendo** [comment]
just for future reference did you have to close the PR first?

**Comment by zootechdrum** [comment]
what do you mean by PR?

**Comment by grafkendo** [comment]
did you have to close the Pull Request(PR) before you merged in the changes? I was not able to even pull it down until you cleared it.

**Comment by grafkendo** [comment]
anyhoo I don't mean to distract just curious. glad it works!

**Comment by zootechdrum** [comment]
really, Interesting. No, I guess you cant do shi% until that is fixed. Good thing to know! I did not close down pull requests. I guess its a feature of github. Makes sense in hindsight. @grafkendo

**Pull request merged**
